# config/meta.yml

meta_product_name: "Freelanz"
meta_title: "Freelanz - Projects at your fingertips."
meta_description: "Find a project in just two clicks."
meta_image: "freelanz_screenshot.png"                       # should exist in `app/assets/images/`
